name: fluttershow_keynote
description: Package for FlutterShow framework that recreates all types of slides from Keynote with variations.
version: 1.0.0
homepage: https://github.com/lucas-goldner/FlutterShow

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fluttershow_base: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
  assets:
    - assets/fonts/
